name: CI pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.2]
    env:
      "ADAPT_AUTHORING_AUTH__tokenSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      "ADAPT_AUTHORING_CORE__rootDir": $GITHUB_WORKSPACE
      "ADAPT_AUTHORING_CORE__tempDir": $GITHUB_WORKSPACE
      "ADAPT_AUTHORING_DOCS__output_dir": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      "ADAPT_AUTHORING_MONGODB__host": "localhost"
      "ADAPT_AUTHORING_MONGODB__port": 27017
      "ADAPT_AUTHORING_MONGODB__dbname": "test"
      "ADAPT_AUTHORING_SERVER__host": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      "ADAPT_AUTHORING_SERVER__port": 5678
      "ADAPT_AUTHORING_SERVER__url": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      "ADAPT_AUTHORING_SESSIONS__secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1 
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
  
    - run: npm ci
    #- run: npm test
    #- run: npm run lint
